feat:Add live chat.
hilaldedek/pentagram_blog-app pull request #25
Opened 2024-04-08 11:20 UTC by hilaldedek

2024-04-08 19:05 UTC, DurmazDev commented on client/blog/src/pages/ChatPage.vue
> +          `http://127.0.0.1:5000/chat/${this.username}`,
I think domain names should not be hard-coded & some print's, console.log's forgotten.

2024-04-08 19:11 UTC, DurmazDev commented on api/app.py
> +            new_message = Message(
Saving messages and message rooms in a database that can be created by anyone as many times as desired can be costly and may cause the database to grow. Maybe a cleaning mechanism could be written.

2024-04-14 14:22 UTC, dilekyalcin commented
I agree with what Ahmet said, otherwise LGTM

2024-04-15 09:29 UTC, gecicidegisken requested changes

2024-04-15 09:29 UTC, gecicidegisken commented on api/config.py
>      JWT_SECRET_KEY = "!6uad-[aadşawlmdşwaödDArKZ8zp0V3bfXzWxW:ffhn7JlszRG9e;d6-HcCya"
JWT_SECRET_KEY should not be exposed to public. It's a crucial security issue.

2024-04-15 09:29 UTC, gecicidegisken commented on api/tests/confest.py
> +def new_user_create_3():
I don't get why 3 versions of the same function is needed. Could use a different approach here

2024-04-22 10:02 UTC, closed without merging